---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-root
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: homelab-root-ca
  secretName: homelab-root-ca
  privateKey:
    algorithm: RSA
    size: 4096
  subject:
    organizations:
      - Homelab
  duration: 4380h # 6 months
  renewBefore: 720h # 30 days before expiration
  issuerRef:
    name: selfsigned-root
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-ca
spec:
  ca:
    secretName: homelab-root-ca