apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-manager
  namespace: *app
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: "v1.19.1"
      sourceRef:
        kind: OCIRepository
        name: *app
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 15m
    disableWait: false
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      podmonitor:
        enabled: true
    # config:
    #   apiVersion: controller.config.cert-manager.io/v1alpha1
    #   kind: ControllerConfiguration
    #   enableGatewayAPI: true
    