---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neuvector-core
  namespace: neuvector
spec:
  interval: 15m
  releaseName: neuvector
  chart:
    spec:
      chart: core
      sourceRef:
        kind: HelmRepository
        name: neuvector
        namespace: flux-system
      interval: 15m
      version: 2.4.5
  install:
    crds: Create
    remediation:
      retries: 5 
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    k3s:
      enabled: true
      runtimePath: /run/k3s/containerd/containerd.sock