apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rancher
  namespace: *app
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: "2.13.2"
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 15m
    disableWait: false
  valuesFrom:
    - kind: ConfigMap
      name: rancher-values