apiVersion: v1
kind: Secret
metadata:
    name: homepage-values-secret
    namespace: homepage
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:IwVlkCoNGnFPQ8/O6jvxbtj9pJGmu9zJmajCJ2VQYfyJbpFvmRnJ28T+5eZI4DYoQsbEswL+hDNQs5pOFQzZuskryxo7izNmuKaoBpO8jn1m3FQBcy2xK2LGnJ7F6MXDgvbnSLubiOU5lfX/xbxG5EAktUmUlAm+ZqglPh0IxuF1tEON+04F6Il21jr1ESz9jRBSEWAiSJOXH2Z7rfCjfOBEqMEeQlFIXzI+cqycMKBowqIPuLwwl5WYmVTzvYs9qZdgDOO+6qyd9bHZUGzp+DkjmcUlXjQGDLYhZrXmhUsk3zbtTRTHTF4S/DqwR5yzk6fSCxK67j+UWCKCPoP0O7M9O49kwf0xYqCLNsCwvpi79OQe/Gy/P4lLLnEjvxqRpjz7Zm5P5pNFZlHhdCyE6eitVAC8scMJ1Gl5Rcc8acKWVxZh+CwLPCX1gTsEqXSEP0NwdIOSZ3tWBag7qftakI7xEgMzxorACWRwOgnAATJMRak/6NDVzPSAuyx5HZxqtu9352uxVpmECpDgjL1XXf6XzU79KqyG04HWXOSZjanIHz3louKEUVhHSnrfcKPuKnxhlhBet8ih37k8XFjN3ZGR7ak6ZXkBCR6lBZaSLZVpQ59kLvju28SMheYm0cmWcnd4mqI71LWtkKXWs4Ssme4C11cZ4aotI1oeGLgqn5UWymVYjZ20RzWbJMmTUWHut+hAXZ8TxBf3qbFaGx5dm3IhyZyGPs8uriE2tTT/Rj0VvsFSXxtsAhZkoh8Rexrs+EX9KfRsBJnvscKdHWan29Z1lgaAGcC6klecS6I88DjD85svQdiYMDyBp9UO6jgsvsKcxOjv7nYsKAWlEXhBFq/7e8V0bMI2cRbPwvecfr+JXyi59obtIKN+nlSrblGv03CJkZ7X55Q9XF3m6buGmhwkDyKsoh7zSrwU7Dz0sg9204avNmigrpY+SZR6FmefM2dVmIXLqKYGz8afu113lmUMda1jVFMBlLsdi5JN070scLbDc2HPB742C2CIGJZW6iFXvGMRoYiE8oSx4Fl05wQ7FWPhEaW5byExjg==,iv:hkk2zVSkvYC/zTVqAOm9HQDAd+LhiEzqtgK7n90t/3s=,tag:TASKBaw6zcEhS/XnoynDUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-17T21:01:56Z"
    mac: ENC[AES256_GCM,data:XE7tjKbLVSsH3I7qjGeBbq7HJsf/uT/wziGRPXLI//xp7T4EBVdv/HaARheTE34N7dc45R29ncigzqGY6EDJ6s9YSJ+k2peOVQiE4f7NBVGsJVb/d9dtezYgXammzY5n9gpFHD/dpkfOvy0feHVixvczcnrf9ODFpatvzr2SkoE=,iv:nFbBMb84Ro0X8amNBUeMIRmWRyd+WnlpgFx7ZHog7Fw=,tag:aAerOufZ4jzv8Lvjq9zg4g==,type:str]
    pgp:
        - created_at: "2026-01-17T21:01:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAybZwhlimvyVAQ/9HYvUYAgtLk65xtcewxEoc+ADXzbBnDPA+X9+LYUONnIn
            z42FdNd65PdNzr0+O/onNy30lWkgcc1SkC8vV0rG48rmwPgwHGQbLn8jBcthIA4O
            o0TJS21jVGajij+X9pEWVAtI90EHUPrFCGmlHXbq0JL0taOVz97AKmU/pftfIQK/
            riYyp0d+P+X3gL1lrZwZj9lmnHF6h0KepH+MRkv4RrX2e2itdmICFmHIOJbjXKrk
            RYPUTY3fmIz1ba99MpkRMXlPybtIZfAw24Wdad6XH6RCZQyE8vmkGxaC2VxQnKVj
            U7+UbxcnvuLXLJIID4HGD6IIytnypO5z1B1IqaWahKaE+X7Pj5vBbFGVSK+EuyvV
            c54pDHq9B4qh4S32Z42VfDBKKnwxNtwZ8RUiObxE41Qg0tNMHvfptY1WJPoTdWkZ
            TNW+7vD3sjLu49FDFaR66PMSps0/oT7+CZRAGkmDUEKkkPDBw1t0KS1esTjj7C+O
            BSRpKP+f1WTVwKMIhOER20luxzoARXP2dbIZEfrln0dbknhUiLazitWhAM8Z0c2s
            NNuSIFY9vTwTLqAMl29G2u3IM4q/iIvbJdk6Kr1OpIfIycolu67518BUhTKJ3FSn
            i+KdaP6qsR6TLJZ1/IDC6XmhIOTi6G1KJXfWWynJerpqSXQxtKn2qSvYX/caRSbU
            ZgEJAhBzUW/bLBMRSJ3eL6wbPRA/V5SLVbylUg/P5zYs6+1lLlT23ohjZf6qCjMP
            Oef8aznXpUZldpF/3RdaBsTfGoRTFxOAAzNgKVv3JSYs0pi2W7ifQ/iDnXnIOBww
            C2c3mMPa1w==
            =VNR1
            -----END PGP MESSAGE-----
          fp: 61026EB60835C9F13F6A9990B754BDB32786572A
    encrypted_regex: ^(data|stringData|env|password|token|username|email|auth|clientSecret|accessKey|href)$
    version: 3.9.1
