apiVersion: v1
kind: Secret
metadata:
    name: homepage-values-secret
    namespace: homepage
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:6sotgsp5kXruCTEUrXE2VtC0IPD0rg7T+Snxwak5+uKTgxfQStpOdKtYJ4vbESs/zGmDW3DKi+pmYUwkQ+g4N826vgbGtY6+zPR5Xyp1fiqx8/JGvXvxvf9q5wZuRSn4R260W8Zeud2JXcqssDVtC9pjrOJ7I5x/MhpX6iRwrKwWKIopZYHSRsqjUkhR1HJ8NrtTqcyJzbT4dkF5wpd7KGe/OfET+SyACqTt/Or5VZgxRNlucfPJXGH+4wvROEXCC8CR/gDRm60c8Xlq3M2fq344xYDYAIitzOjJ8Sn0uZDWnvf27y6CAEZsvnfPxl3KTu1PmvwEQZrTnBTH9VJqdQMfRKudSGcHcqoDZJg0SsFCjvVrhvRfCxf+eZkB+qLqe0TVS7GEL34DbT10I10fa7QXW9tFk5OLfMKeI4e2ecfor6AMBfhGADtpO64V9ctunag9E0JkfUoPjMRFVhaVmgKtjmnCqtSzgy9spzdcWu7oS/PLzdgja1X5keYblHrHb+EWAcuZl7wt9PWXUfRBXRgUV1VhkCEwbriCrg/ewmWAWYrbXhII/KyHv28SiWuFO3ymEvbQmZVNtX0JOP1V1AMlSLwqfff2s8t7P+XgGIC/ZvV2Fzf2Ksk2bcRNmVmAiIfQb3JepZY5GC5uzQ3GjS7NwemiBijckJU5DXhR4RF2+cEARVBtOwAXdux5LnTNdLImgk3IuiFnHJsh5NGPQy3Gzwb8QcszkGxml3+LbLVTa1f6qU/+EyHYopMreA5f3e89kPCyYWIk7LHY0bWp76hnrUCvNNOgUAVWRPt+vlsRTEL6TG9oId90hdmnhSmQhpNshKZ9VhNKSJ0g9WnZfbzKQ+BxJtRPlo3Au/6glX34/rQRfftS3bKpruHaKCF7vTDh7lrn049KZIQs/P9JNfEBDmwANwWlO4NU4DlyHvOKXypJU4KCG80ZZ1Fc1Q2zhu06Qpenr2SHyQO8kYfIiz+lA7AY5eEYYDjGwiWDLEN5T5HTSJIEOLfpYHCteGTX14TwsY25WnoQgpDVrJHFtIQxVgvaqMRB40egsdBA4wDn8a4V1bGHEQs2RAorPTPJVPHMUDm83hgA7jlArKqJaLRyfEh34+MbOtIAQpxLwPKFOG++IGAT2u1zaLIuSV4Z+tIxqde1Cy8Ao1KXCg3RWdhoflKZtuTdh7AuLlb4I82Scwi3aQM3Vr1GevvRdY1ij4HuD/3atFNRjLdhTXbrSr6uZlFsJabS4ieSYKysqYOQpj4IkGwxwAFbDm4hb87fYVvnGVpF5clEetEP5thH3ZihTsx5xzqPjjUI3xn2LtPiR/QeH1R6L+OvCel9WuVg5lmsXb3Bb/sjpWXatZC8JDh2QDZmRvSCkgJa+VoTbjHZqEOlOW3I1hYFgxHRxAlWNw113+6Nbuk67uxb2HJHMNMAlt5L6ChmBY0CyjCP4XmB69YxEt5RR7Rm/lMDU1UkZ3/JH2FqdtEiNVVZv+4PEojsZwRfFb0uIKsjnYpQamTLOoqxmnR8Hl6IZ17d2Wo3/saSYA06,iv:C8N5kM9sJFnoMHMPsz9MUW6e1G+M+kBFPpU2e4AWopc=,tag:8ixnNGiFdG/sUGZNAAaGyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-18T04:00:21Z"
    mac: ENC[AES256_GCM,data:GQ3mzWK21vw2URIpqOdK/psQW79PbgF99FypEv+ZKYzpiSO4ThyPaopzrahBoQyea5PVtaZ4tw3ZfUNDQweIjICFcTnTRud+WgaHL88GQ9OFNXD1pqeK/fEU+CvzygYXXJYV31axHx5hjiv0gxYykM3Q6nswp+t3KS2lqAJtBZk=,iv:k1kTul2rWn7kzz16QrFUTvRptZh9qcz6uWSjsV7FwmI=,tag:7BFWmXOszTWEAjCKMSfpbQ==,type:str]
    pgp:
        - created_at: "2026-01-18T04:00:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAybZwhlimvyVARAAiLGgzJovim68wmo4poZa0LrGyxdndxGUAPuHqF3yNTBb
            /6q2Yb5q1R0rQyELXExBWQvzfMS79RA1tdWXm7FR8Rh7x6M9CHjnJ8AfGzA0GdlI
            JqK30FQMxtlpzrM3xgnc6SoQWHBrYjnP5Y3Oik/C//nFy4w4J3qq+wX39N3mF+mQ
            QB7mdwKPgakaO4FhPjJetwy81RLrVlP+x9QFGADEgL+WKtxzNnM7JwvRRSMcQz6g
            SDMEdyoT2f6lIjpAO4K8q2qDZ3f3vt8c2Z8xHKxWZHa1s1X1iUAglOGjj4zrBq7q
            SyUyJl0kL12W3XJVSpnTxdX4nYtQE40XWb4alyLUcNiJDFEX4pQ8orwDO6sRgbCS
            onl8X8+JjX5mA8hhInHQOxD0ZOiZSGngOXcJNV5eVo6O8i+GVE5arIc4zB5IKC7Z
            R/5gWoVg51gH4IlJu1Iclz4FetsV61NkY+6ltkNGAUkU4ghI+czs57Jtb7m6iQKg
            l9nPEX9V4ebWaBXUyBc20OMTzvfR+b7eG9lmNtmYG1pWqzxtoDDCi5QQZH074/fo
            EG37BKSoHXW4mBQkGmvvy8iUeopIObXJk+mWjOmQGgHZ3hB5aJmwtx+7w9yBCNBT
            Z5OEmYURcNQzXNQL1tZq29y99uLz9bfiGv45M4WXfObwhyjAUkD7krNDqC8y2XjU
            aAEJAhBO0lc66G9aZB5Bs4JC0HjBCb7FqrGmG3tSBk4U/vpcQdsriA5FuWy64bn8
            F2hO6cBUzLK7lQOuhslVd0zDwYgxHCxaZTsB2wVPTljI1lG63gAnluQYlSRXoKOl
            q5Vj2kcqrQTJ
            =J1xF
            -----END PGP MESSAGE-----
          fp: 61026EB60835C9F13F6A9990B754BDB32786572A
    encrypted_regex: ^(data|stringData|env|password|token|username|email|auth|clientSecret|accessKey|href)$
    version: 3.9.1
