apiVersion: v1
kind: Secret
metadata:
    name: homepage-values-secret
    namespace: homepage
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:rVt8YmEl9RYktDO5iZL2/kTj5CHMCJAlICDco7JZ8VRIewPLRBpQGiFLWDIsoWe3BQm/fTXQ0xN3v1fDSjvrxKMaltFYff9viKKTiXKqV8UXWtW2H47n5QR+CM56GhwsMxXlKXR6xBZyazlY/fIq5rb3UG+X3titLdyjPBHW64iwZCSviBJvzjYhVmZHUlvdu7Naugwt45jVLmGYW25774WFbWAKeZljz8hGyEc1aiDjpxM1F550Do6g+FuxmjAZtei83sDNg5KWZSsPIeyrsyBVzrT23+DqV+Av3ntw533hRXi97YEE9Est5FuDOvcT7rEDmMfqld8mkkTW0DwuwxCgAGJ7yUcQiZ4JiFr5En1biw5vAW0evNFw6JtfjEsJEKn/lM2Qj+2PjFS88/T3RLSCnI1nlPNuYo46iA/CetAC+mojO0aW6SibSYweeFDWJZceOWC+4qAGUkazR3Ld8XPpzMXkOFXTjyt3CpYKJHijcM6QG8fOr0KM3ntb/NnQ0Vul4iIXoFTLbwQ6aCF04o1eJrs3JQHy22xwLq3/qJIJVyX4gR9jFGrc4Xqth/WNt3iakfAeWiRHk4CDwOotDIBBwbeVc9YfDlMNAX0l40c9TIeD1T3U8HosR6dc2r8JRB8pccTF6EHFJrJjqZEikRlF7J1sKennABhkj75Z1HrLiGkhQEEtw9/0mxIdeB/0i4I/mOMMry0dLMSwaFF17/00Qh/OmNSxXw8tnXdwl0+Re7ZX2lYGxurAv+icpefFGnY/8JrHgE5V575tu59ddgyTDb/C3qpcwNj+NZzVxeWGh43wcEVMaD+WBqcziHtmNGzzzZ7iDNxrouNWaNRvLeWL/otduhQJiXxnrq6uwwfH54qW7eJWlEWLGq8VYE09KTVkVISZ1+xHZIHu7cltscWlFtu0vO2HHVdn/jk3FoNz87mD4iU/Rm2mJ+VqxqUvr/dj2nOf0utO3P0/P8uoNSrc0hmtdbSq+suqHC78I+qDXB8IYzRJD2iYraYynl2pBX5YSdkqj0wl6LGM7lP/cXWxKjsJNXc9gigVQE4QGee0reZWUXgocfJXy+GGrKFknUTGPr1q1pu1jA08CicFvH1/DlW8UAo7hy5bPGDCqlMhp+6Mz9S/dOqW9fLTl/gQvDQgn63TkEsjqtGI0tcpZF4rKv11OmSroBUxJmVh,iv:TKERlmjmgvDqmNuiDvQUEZnGJV1RLIcysPsZ/oO0E10=,tag:qEvJEDa1+0oxwV/ZQ001jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-17T22:51:51Z"
    mac: ENC[AES256_GCM,data:snfQ0PyPE3QYqD2n2nuJ/8Kydn2rmXYLA7zrxEPTiNWsr/M/uilmOECoSwHxR/wr5/1OdW8gQb0tboR5bpTU9irAy0+8toc6hyxhd2478c71UsgC8VAI0yKlh2cMlk/MGHjre4+7koP/MQOX58QYvFllWoH8cWQy0mSBtNbnbyY=,iv:ZEJB3bRZl2btJIK6KCJaE0wINC99TXomRhLMvepP0qM=,tag:qHPj4wgsOdqlHUCvqHeysA==,type:str]
    pgp:
        - created_at: "2026-01-17T22:51:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAybZwhlimvyVAQ//YWsQxl9VY86hAgk/7JqKUzqTiWbaNbIcADarXjzBTLVP
            zl3PoHD1s3/HeVCwt0bmFZVtdgCqyHFIveiQAlhdM+E2mLhGcqRsOLF0vE/2dMV6
            045fhuFFKsJILNVE29ZvE1jKIo1Jz5IHXSE8HR2X8W6I27FRl/PMS0NLg2TmVhkW
            THKJ0zkyK52BpFheEAXzmwfV6DH/MMMvTs4JC6KME70l8Dy7cO7m+ECpwZYsP+X0
            J+Rg3HABM2K92Yht/0fbWvUiIdmq4c3MrI36LeL+Rgtmc9/U51xtR1EpAF9TeZYe
            Q6vBSSGMvoLdR+RVDsCpMgu6FK1bWuwybZRljMdMSRuNXdj/q82+pHGzXQo1aTcD
            h/vJCuicCBQ+29xsdVnZiiVl1KQgxBr/JVJWmFARbSAqIhp/MEZXk6/CW+NoZu4l
            TIAXYvfKOIau+kaOQjvnjFMgbck5rbatYjCI1/xGkAxgRcFm0qAw5WL+5BlMSt1m
            NSg7L7cT+9hKv4R0W6iuQFBa/DVP8N3mC8ofjLdsyNIdCsIp2A7ckbvppArOXCSL
            uy1Wtmvy8adMF3GU2nTB6nwtr9wpMV2r1Ez3k6dXSoIKY2bf22E0evcIbiYxERpW
            8DqfzAHILh5it+fL06sItSzgK1CT1Sy6sqjxutMWt7xeyK7a6j46RYKppYqEepXU
            ZgEJAhC7ny6BwgHzvs+3h9yarLV20t8NGzSlgG1ugbh7zjyaKq8ZkLQSMyduX3pw
            U0IJrh7KWAiYHCRcM6D2UVjkpeGKVUVRClpEIA3S3vf1jmHZwaBpKCwTiDUSbF2l
            jaTHEc40Ww==
            =Go+N
            -----END PGP MESSAGE-----
          fp: 61026EB60835C9F13F6A9990B754BDB32786572A
    encrypted_regex: ^(data|stringData|env|password|token|username|email|auth|clientSecret|accessKey|href)$
    version: 3.9.1
