apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio-tenant
  namespace: *app
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: tenant
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  rollback:
    timeout: 15m
    disableWait: false
  valuesFrom:
  - kind: ConfigMap
    name: minio-tenant-values
