apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: harvester-seeder
  namespace: harvester-system
spec:
  chart: harvester-seeder
  enabled: true
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  valuesContent: |
    image:
      tag: v1.5.1
    fullnameOverride: harvester-seeder
  version: 1.5.1