apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: addons
  namespace: flux-system
spec:
  interval: 10m
  path: ./addons
  prune: true
  soureRef:
    kind: GitRepository
    name: flux-cluster