apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rancher-vcluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/harvester-cluster/addons/rancher-vcluster
  prune: true
  wait: false
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system