---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cert-manager
  namespace: kube-system
spec:
  interval: 15m
  releaseName: *app
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 15m
      version: '*'
  install:
    crds: Create
    remediation:
      retries: 5 
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5