apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  labels:
    addon.harvesterhci.io/experimental: 'true'
  name: rancher-vcluster
  namespace: rancher-vcluster
spec:
  chart: vcluster
  enabled: true
  repo: https://charts.loft.sh
  valuesContent: |
    controlPlane:
      distro:
        k3s:
          enabled: true
          image:
            tag: v1.33.5-k3s1
      statefulSet:
        resources:
          limits:
            memory: 8Gi
        scheduling:
          podManagementPolicy: OrderedReady

    experimental:
      deploy:
        vcluster:
          helm:
            - chart:
                name: cert-manager
                repo: https://charts.jetstack.io
                version: v1.17.4
              release:
                name: cert-manager
                namespace: cert-manager
              values: |
                installCRDs: true
            - chart:
                name: rancher
                repo: https://releases.rancher.com/server-charts/latest/
                version: v2.12.2
              release:
                name: rancher
                namespace: cattle-system
              values: |
                hostname: rancher.homelab
                ingress:
                  tls:
                    source: rancher
                replicas: 1
                global:
                  cattle:
                    psp:
                      enabled: false
                useBundledSystemChart: true
                agentTLSMode: system-store
                bootstrapPassword: "1234567890"
    sync:
      fromHost:
        ingressClasses:
          enabled: true
      toHost:
        ingresses:
          enabled: true
  version: v0.27.0