apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: *app
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: "v1.8.1"
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    timeout: 15m
    disableWait: false
  valuesFrom:
    - kind: ConfigMap
      name: homepage-values
      valuesKey: values.yaml
    - kind: Secret
      name: homepage-values-secret
      valuesKey: values.yaml