apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin
    namespace: nebula
type: Opaque
data:
    password: ENC[AES256_GCM,data:PkHkxkUaUzBqX3YcOUwtMw==,iv:1dEnziWuHjMLSu645ZpSMBZs06wt+yrRB7D6/cR/KEA=,tag:zulD5kcfnpEjaBaBaLyihQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-30T02:58:16Z"
    mac: ENC[AES256_GCM,data:PabsjFKsPprQyVzuBIQZ5jbhRFwTagHnSUVJq12pQEsu1mX4mC1TevHFSoaD+szOMHXfNRjnuUMgXtQ8RuHKOjrk9zV1SHSqCcNe7NJn8KdFzA/6ebP4bFT43qynyyrkvKQyzmFAe7fqj8rpF7FcRcvRbMY6+cNP6skFDOzh144=,iv:+VrscemZDPO4nKUa+2Y+wWl6AbQyvI3KmO6NitX6Zls=,tag:vaaAe3bp4AQSx1AvuGGHrA==,type:str]
    pgp:
        - created_at: "2025-11-30T02:58:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAybZwhlimvyVAQ//aUqNO06nGVnd8uajI1m8AWTao5fv8ITgj/X8uVBReUVy
            8hkh0i12EqbjZNkY5J8w72YMibM0sphn4EsTGhrO2qdPOuu1zIE9hDF5y5Lb+l9E
            ELeleg3DTI4z0poR4CyBh4M3LJBi6mupW2tbqWND9FFuqoq8tuRFL9XTHqe+iMT6
            NJ1Gz3BR2HbEU9dK67GehPMSVMz6DD+Vffn3ni+MzdUx6tid8iVofxPXcW57ZD+8
            zSYYFbMnihUN4m1eiydyAhDPiiFYCDuAOO6YT+hgfXMYJy5o8yyKMQpNfx0ulxYS
            aB3qxhc6e+etNVU2gYF57W9if8A9PU6VmLmRJ3ksnZX7PoQlrlPT5QIif89dp+ab
            i/rAIukdYhUsqy+HeQh8T9tqPl4H+cHhkQp3Ms59sEMk5vYpnrEO4CeCsZOp/NIJ
            kDMhjd13GVGz9sXgxsJSu+UysLqJRszmuhB6GZfEb4vCL/0fL8UKTvRlDQxMaoWP
            jlzHpwfIJbIndA2+Wxm6iLdqXtISLqku+wLU+1mkvEcZ2JubacmPaSmF4KtVc7bK
            kT6ELbNUSxtHLe81qq5kD8zmh2kvSTNPXtbFfdAry5XjPM1Luwh1mLDeUUp7WeRh
            hmYHUCwuCowopyFz8V6c5xisA3Pl46Khu5lTdK6uAiXNWyxy2jYH34461myxRL3U
            ZgEJAhAbGybK62SP5fx39xxw9tfZ5Hgyx1a3zvHns+AKcsI28EBW97mi6VcpkKsv
            J10JctFfgc7s4G36q1Q/m/nZw2I2OirH4pIdC1DOk+3R63J/exHqyr/BoV1Gc04z
            ZUw8qzzZVA==
            =B4Eu
            -----END PGP MESSAGE-----
          fp: 61026EB60835C9F13F6A9990B754BDB32786572A
    encrypted_regex: ^(data|stringData|env|password|token|username|email|auth|clientSecret|accessKey)$
    version: 3.9.1
