---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app rancher
  namespace: cattle-system
spec:
  interval: 15m
  releaseName: *app
  chart:
    spec:
      chart: rancher
      version: 2.9.3
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicas: 2
    namespace: cattle-system 
    hostname: rancher.deiberts.domain
    rancherImageTag: v2.9.3
    useBundledChart: true
    agentTLSMode: "strict"
