---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rancher-latest
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://releases.rancher.com/server-charts/latest